fixtures:
    forge_modules:
        sudo:
            repo: "saz/sudo"
            ref: 3.0.6
        base:
            repo: "tsuru/base"
            ref: 0.0.4
        python:
            repo: "stankevich/python"
            ref: 1.9.0
    repositories:
        "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    symlinks:
        "gandalf": "#{source_dir}"
