fixtures:
    forge_modules:
        sudo:
            repo: "saz/sudo"
            ref: 3.0.6
        base:
            repo: "tsuru/base"
            ref: 0.0.5
        python:
            repo: "stankevich/python"
            ref: 1.9.0
        multitemplate:
            repo: "deanwilson/multitemplate"
            ref: 1.0.1
        apt:
            repo: "puppetlabs/apt"
            ref: 1.8.0
    repositories:
        "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    symlinks:
        "gandalf": "#{source_dir}"
