fixtures:
    forge_modules:
        sudo:
            repo: "saz/sudo"
            ref: 3.0.6
    repositories:
        "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
        "python": "git://github.com/stankevich/puppet-python.git"
    symlinks:
        "base": "#{source_dir}/base"
        "api": "#{source_dir}/api"
        "docker": "#{source_dir}/docker"
        "gandalf": "#{source_dir}/gandalf"
        "registry": "#{source_dir}/registry"
        "router": "#{source_dir}/router"
        "rpaas": "#{source_dir}/rpaas"
