fixtures:
    forge_modules:
        sudo:
            repo: "saz/sudo"
            ref: 3.0.6
        multitemplate:
            repo: "deanwilson/multitemplate"
            ref: 1.0.1
        apt:
            repo: "puppetlabs/apt"
            ref: 1.8.0
        stdlib:
            repo: "puppetlabs/stdlib"
            ref: 4.3.2
        python:
            repo: "stankevich/python"
            ref: 1.9.0
    symlinks:
        "base": "#{source_dir}/base"
        "api": "#{source_dir}/api"
        "docker": "#{source_dir}/docker"
        "gandalf": "#{source_dir}/gandalf"
        "registry": "#{source_dir}/registry"
        "router": "#{source_dir}/router"
        "rpaas": "#{source_dir}/rpaas"
