fixtures:
    repositories:
        "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
        "apt": "git://github.com/puppetlabs/puppetlabs-apt.git"
    symlinks:
        "tsuru": "#{source_dir}"
