fixtures:
  forge_modules:
    sudo:
      repo: "saz/sudo"
      ref: 3.0.6
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: 4.3.2
    apt:
      repo: "puppetlabs/apt"
      ref: 2.4.0
  symlinks:
    "base": "#{source_dir}"
